spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tasks}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    enabled: true

  web:
    resources:
      add-mappings: false

app:
 cors:
  allowedOrigins: http://localhost:4200

security:
  jwt:
    token:
      secret-key: ${SECRET_KEY:word}