create table users (
    id       bigint primary key generated by default as identity,
    email    varchar unique not null,
    password varchar        not null
);

create table tasks (
    id           varchar primary key,
    title        varchar not null,
    description  varchar,
    is_completed boolean not null,
    created_at timestamp,
    finished_at  timestamp,
    user_id      bigint references users (id)
);

create index index_user_email on users (email);

-- insert into users(email, password) values ('rrggo76@gmail.com', '123')