version: '3'

services:
  kafka-1:
    image: bitnami/kafka:latest
    container_name: kafka-task-tracker-1
    ports:
      - "9092:9092"
    user: root
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_KRAFT_CLUSTER_ID: e23dc448-3234-49ff-a345-021e62e40a3e
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092 #Внутрение порты можно вообще ничего не менять
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9090,EXTERNAL://${HOSTNAME:-localhost}:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - kafka-1_volume:/bitnami/kafka

  kafka-2:
    image: bitnami/kafka:latest
    container_name: kafka-task-tracker-2
    ports:
      - "9094:9094"
    user: root
    environment:
      KAFKA_CFG_NODE_ID: 2
      KAFKA_KRAFT_CLUSTER_ID: e23dc448-3234-49ff-a345-021e62e40a3e
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9094 #Внутрение порты можно вообще ничего не менять
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9090,EXTERNAL://${HOSTNAME:-localhost}:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - kafka-2_volume:/bitnami/kafka

  kafka-3:
    image: bitnami/kafka:latest
    container_name: kafka-task-tracker-3
    ports:
      - "9096:9096"
    user: root
    environment:
      KAFKA_CFG_NODE_ID: 3
      KAFKA_KRAFT_CLUSTER_ID: e23dc448-3234-49ff-a345-021e62e40a3e
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9096 #Внутрение порты можно вообще ничего не менять
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9090,EXTERNAL://${HOSTNAME:-localhost}:9096
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    volumes:
      - kafka-3_volume:/bitnami/kafka


  postgres:
    container_name: postgres_db
    image: postgres:16-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tasks
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "docker_app" ]
      interval: 10s
      timeout: 5s
      retries: 5
  postgres_test:
      container_name: postgres_db_test
      image: postgres:16-alpine
      volumes:
        - postgres_test_volume:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: tasks_test
        PGUSER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5433:5432"
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready", "-U", "docker_app" ]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  postgres_volume:
  postgres_test_volume:
  kafka-1_volume:
  kafka-2_volume:
  kafka-3_volume: